### PR TITLE
Add other answers to translations

### PR DESCRIPTION
**Pull request by benjefferies**
1. Run translate on schemas `./scripts/run_translate_all_surveys.sh ../eq-survey-runner/app/data`
1. Go through welsh census_household/census_individual schemas to check other option text

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
@benjefferies can you update the README to either remove the setup part or say you don't need to do it if you run the script as it does it for you?

**Comment by jonnyshaw89** [comment]
@benjefferies i ran this on master and can already see other labels in Welsh?

**Comment by benjefferies** [comment]
Double checked this on master and cannot see the radio/checkbox subtext as being translated. Could you recheck?

**Comment by jonnyshaw89** [comment]
I was looking in the wrong place.

**Pull request merged**
