### PR TITLE
eQ-1375 Update extract and translate without sections

### PR DESCRIPTION
**Pull request by shahi645**
### What is the context of this PR?
In SR launching a survey in `cy` fell back to english due to `sections` being removed from schema. 
Changes in this PR reflect that change in SR

### How to review
In SR run in `scripts/translate_schemas.sh`, edit line 9 so that it says: `update-extract-and-translate-without-sections` instead of `v1.2.0`. 
Then run `./scripts/translate_schemas.sh` from cmd and in the data/cy folder the welsh census schemas should be there

### Related to 
https://github.com/ONSdigital/eq-survey-runner/issues/1263

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
@shahi645 it looks like the block titles are not being translated
screen shot 2017-10-04 at 15 34 43

**Comment by jonnyshaw89** [comment]
Also the Navigation links are not translated. But that is probably due to them having been moved into another part of the schema.

**Comment by shahi645** [comment]
@jonnyshaw89 card in backlog to address section titles in context of spreadsheet and navigation section

**Comment by jonnyshaw89** [comment]
@shahi645 try not to squash while PR is in review. it makes it hard to track changes

**Comment by shahi645** [comment]
Sorry!

**Comment by jonnyshaw89** [comment]
@shahi645 what did @charlotte-hirst suggest regarding the block titles not being translated?

**Comment by shahi645** [comment]
block titles now are translated, navigation unchanged

**Comment by jonnyshaw89** [comment]
screen shot 2017-10-10 at 13 14 20

**Comment by shahi645** [comment]
@jonnyshaw89 
block_id had changed, context updated and both titles are translated

**Comment by yoganandkunche** [comment]
@shahi645 Looks good on census household but the above translation mentioned by @jonnyshaw89 must be done for Census individual.

**Comment by jonnyshaw89** [comment]
Thank you page is not translated.
Is that expected?
screen shot 2017-10-11 at 09 34 11

**Comment by yoganandkunche** [comment]
@jonnyshaw89 I think we never translated the successful submission screen

**Comment by jonnyshaw89** [comment]
@yoganandkunche it is still content in the Schema. @shahi645 do these translations exist in the excel file?

**Comment by yoganandkunche** [comment]
@jonnyshaw89 thank you page translations are not part of excel.

**Comment by shahi645** [comment]
ill check the old spread sheet, but i think it was not translated previously

**Comment by shahi645** [comment]
@jonnyshaw89 @yoganandkunche submission successful page not included in spreadsheet, so was not previously translated. I did raise it as part of the card for future amendments/improvements, see https://trello.com/c/SyiYWuQp/386-eq-translations-future-updates

**Comment by jonnyshaw89** [comment]
@shahi645 Squishy Squashy

**Pull request merged**
